version: '3'
services:
  dev:
    build: .
    working_dir: /workspace
    user: root
    command:
    - sh
    - -exc
    - |
      gradle run --project-cache-dir .gradle
    volumes:
    - .:/workspace
    - /usr/share/fonts:/usr/share/fonts:ro
