version: '3'
services:
  dev:
    image: gradle:5.3.1-jdk8-alpine
    working_dir: /workspace
    user: root
    command:
    - sh
    - -exc
    - |
      gradle build --project-cache-dir .gradle
    volumes:
    - .:/workspace
